#!/bin/sh

export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

CMD=/app/AudioRouterApp
PIDFILE=/var/run/audiorouter.pid

start() {
        printf "Starting audiorouter app: "
        cd /app
        start-stop-daemon -S -b -x "$CMD" -p "$PIDFILE" -m
        echo "OK"
}
stop() {
        printf "Stopping audiorouter app: "
        start-stop-daemon -K -x "$CMD" -p "$PIDFILE" -o
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
